### ISSUE TITLE
这个浏览器扩展要咋用啊

### ISSUE THREAD

**Issue by hcllmsx** [GopeedLab/browser-extension#1]
怎么安装到EDGE里啊，小白看不明白啊，呜呜呜

**Comment by monkeyWie** [comment]
扩展已经提交到商店了，等审核完就可以安装了

**Comment by hcllmsx** [comment]
> 扩展已经提交到商店了，等审核完就可以安装了

好的，期待！
是不是安装这个扩展了之后，浏览器下载文件的时候就会自动跳转到Gopeed里下载。

**Comment by monkeyWie** [comment]
可以安装了，按照readme里的说明配置就行，有什么问题欢迎及时反馈
