### ISSUE TITLE
Firefox插件添加/保存服务器设置无响应

### ISSUE THREAD

**Issue by EVANGELION-Air** [GopeedLab/browser-extension#11]
同一个windows平台与gopeed客户端，在chrome上安装的插件能正常保存/添加服务器配置，在firefox上保存/添加服务器设置没有任何反应。firefox版本124.0.2。我还在firefox的衍生版floorp中尝试过(所有浏览器设置均为完全缺省状态)，问题相同。

**Comment by monkeyWie** [comment]
确实有问题，等我更新一版

**Comment by monkeyWie** [comment]
@EVANGELION-Air 已经发布了0.0.3，已修复
