### ISSUE TITLE
下载126邮箱附件失败

### ISSUE THREAD

**Issue by ivysrono** [GopeedLab/browser-extension#12]
1.5.6（web版和portable版）

Firefox WebExtension

文件名可以正确获取，但存在两个Bug：

1. 当文件极小（如1b）时，可能来不及取消浏览器自带的下载，导致下载出现两份。

2. 邮箱附件下载所得永远是20kb左右的一个文档，将后缀名改为txt打开可以看到错误信息。

隔壁有个讨论可能相关供参考：https://github.com/jc3213/download_with_aria2/issues/12

**Comment by monkeyWie** [comment]
升级到 0.0.4 版本就行了

**Comment by monkeyWie** [comment]
@ivysrono 截个图看看

**Comment by monkeyWie** [comment]
升级gopeed版本到1.6.9



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2025年2月3日(周一) 晚上8:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [GopeedLab/browser-extension] 下载126邮箱附件失败 (Issue #12)




 
@monkeyWie 1.0.1版会得到一个readdata.jsp文件。

**Comment by monkeyWie** [comment]
163邮箱可以复现吗，我没有126邮箱

**Comment by monkeyWie** [comment]
已经复现了，下个版本修复

**Comment by monkeyWie** [comment]
1.6.10修复了文件名问题
