### ISSUE TITLE
Chrome浏览器扩展

### ISSUE THREAD

**Issue by techiemvp** [GopeedLab/browser-extension#17]
### Snapshots
![Snipaste_2024-04-14_17-28-24_issue](https://github.com/GopeedLab/gopeed/assets/166714685/16ab272c-bfa6-4b08-9b8b-a78e2266179d)

### Log

**Comment by Summer-Tail** [comment]
出现同样问题，希望尽快修复

**Comment by Stannnnnnnnnnn** [comment]
+1

**Comment by monkeyWie** [comment]
升级到 0.0.4 版本就行了
