### ISSUE TITLE
部分特定页面无法下载

### ISSUE THREAD

**Issue by wentlwr** [GopeedLab/browser-extension#20]
比如ToDesk远程桌面官网内下载官方软件，会创建任务，但是始终没有速度
还有类似浏览器书签导出以及油猴脚本打包导出的时候全部不行，软件大部分时候速度还是不错的，这些问题还是邮箱影响体验，又换回IDM了，大佬加油啊

**Comment by monkeyWie** [comment]
你可以先把扩展暂时禁用下再下载油猴脚本

**Comment by monkeyWie** [comment]
升级到 0.0.4 版本就行了
