### ISSUE TITLE
[功能需求]未匹配 Gopeed 时不要弹出，或者作出警告。

### ISSUE THREAD

**Issue by Mapaler** [GopeedLab/browser-extension#26]
### Description(required)
目前当选中的 Gopeed 未连接时，仍然弹出下载窗口，点了下载。过了好久发现怎么文件一直没出现，才发现没有打开下载程序。

未连接时应当弹出警告或者退回浏览器下载。

### Browser Version(required)
Firefox 115.10.0esr

### Extension Version(required)
0.0.4

### App Version(required)
1.56

**Comment by monkeyWie** [comment]
这个应该已经修复了吧
