### ISSUE TITLE
浏览器扩展连接一直是红点点无法接管磁链下载

### ISSUE THREAD

**Issue by PandaFang** [GopeedLab/browser-extension#3]
windows 11 edge浏览器，商店没找到扩展，安装的chrome 商店的扩展

![image](https://github.com/GopeedLab/browser-extension/assets/4337419/afb9e31f-737f-42b4-af7c-1752cdf63505)
![image](https://github.com/GopeedLab/browser-extension/assets/4337419/6003db9c-3f5a-4714-89cc-ebfc9fe8d97d)
![image](https://github.com/GopeedLab/browser-extension/assets/4337419/7e254b22-e3a2-4ff9-8140-7200635c7df8)
![image](https://github.com/GopeedLab/browser-extension/assets/4337419/b718f151-f425-43a8-997c-2e88c06aa19a)

**Comment by monkeyWie** [comment]
服务器地址那里多输入了一个 .

![image](https://github.com/GopeedLab/browser-extension/assets/13160176/a919796b-f933-419e-b668-1368807715ef)

**Comment by PandaFang** [comment]
> 服务器地址那里多输入了一个 .
> 
> ![image](https://private-user-images.githubusercontent.com/13160176/315896432-a919796b-f933-419e-b668-1368807715ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEwODczNTksIm5iZiI6MTcxMTA4NzA1OSwicGF0aCI6Ii8xMzE2MDE3Ni8zMTU4OTY0MzItYTkxOTc5NmItZjkzMy00MTllLWI2NjgtMTM2ODgwNzcxNWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIyVDA1NTczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZGI5MGIyOWMxNGE2NTRhNDNkM2MxMjg5YjM3NjE1MDMyMjY2YWM3ZWYzODVkM2I5MWNmOGZkNGZkYzI5M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z6TEJgKBA8aCdhS11MPK5bZT4ER2ekRI6oMga8PFjf4)

![image](https://github.com/GopeedLab/browser-extension/assets/4337419/72fd986d-ab0d-4820-bc49-e7ccf06085a1)

还是不行，其实那次多个点就是因为一直连不上， 我多次删除添加重试一时的疏忽

**Comment by monkeyWie** [comment]
在浏览器输入 http://127.0.0.1:9999 看看是不是能正常访问，如果没问题的话重启下浏览器应该就行了

**Comment by PandaFang** [comment]
> 在浏览器输入 http://127.0.0.1:9999 看看是不是能正常访问，如果没问题的话重启下浏览器应该就行了

拒绝访问了， 看来是我自己电脑的问题，不过我不知道怎么解决

![image](https://github.com/GopeedLab/browser-extension/assets/4337419/5112c85e-158a-48e8-b1c2-c36607526643)

![image](https://github.com/GopeedLab/browser-extension/assets/4337419/7d3f5516-3928-4dd2-b934-a14b1d5359cc)

**Comment by PandaFang** [comment]
> 在下载器设置完tcp端口之后需要重启一下Gopeed才能生效的，你有重启过吗

![image](https://github.com/GopeedLab/browser-extension/assets/4337419/712cf011-8a01-424e-bcf4-277bb361ac8a)
![image](https://github.com/GopeedLab/browser-extension/assets/4337419/18edf06b-c8f2-4239-b346-17939dc0d76f)

重启过，我原来在sandboxie plus 中装过绿色版，没有用浏览器扩展，跟你报告的是物理机中的安装版，刚刚把sandboxie plus 删除内容了，防火墙中规则删除了， 物理机中卸载重装程序了，然后重新设置了一遍。 这次tcping 端口可以访问了，浏览器中打开可以看到404提示了。但是扩展中还是红点点

**Comment by monkeyWie** [comment]
![image](https://github.com/GopeedLab/browser-extension/assets/13160176/0fde15d0-5516-4d43-9eea-cb89f507adba)

扩展这里点`检查`进去看看网络请求

**Comment by PandaFang** [comment]
![image](https://github.com/GopeedLab/browser-extension/assets/4337419/9f1b037c-0eb4-4dd2-b60c-3493bbfb8bde)

我把 swichy omega 扩展重装了， 现在绿了，但是一直是请求状态，绿点有波纹。 点网上的磁力链接也无法接管， 还是要手动复制粘贴到主程序

**Comment by monkeyWie** [comment]
是这样的，现在直接管了http下载
