### ISSUE TITLE
拦截浏览器OneDrive下载问题

### ISSUE THREAD

**Issue by Tang-pure** [GopeedLab/browser-extension#32]
### Description(required)
  当使用chrome插件OneDrive下载时，下载任务可以开始，但是会直接下载成一个空文件完成任务
### App Version(required)
   gepeed 1.5.6
### OS Version(required)
    win11 23h2 22635.3566 beta预览
### Snapshots
    无
### Log
    查找日志为空，报错内容为拦截失败报错，与本issue无关

**Comment by monkeyWie** [comment]
浏览器扩展版本是多少？

**Comment by Tang-pure** [comment]
在最新版本chrome浏览器和0.0.4的插件上重新尝试后ondrive可以下载了。
同时尝试下了一些别的网站的拦截，也可以正常使用.感谢作者的插件更新。
但是现在google上的插件好像是变成了强制拦截？而不是原来没有拦截成功自动调用自带下载器；期待作者下次更新gopeed程序能添加自启动功能。
