### ISSUE TITLE
设置高级里的api不能修改

### ISSUE THREAD

**Issue by zhaojie970709** [GopeedLab/browser-extension#34]
![微信图片_20240523185622](https://github.com/GopeedLab/browser-extension/assets/39575436/aa0667fd-8ce4-4912-860e-cafb080ea65e)
![微信图片_20240523185636](https://github.com/GopeedLab/browser-extension/assets/39575436/a789693b-b9ee-4e5d-82e3-2f8ff9173ee4)

**Comment by zhaojie970709** [comment]
docker版本1.5.7

**Comment by monkeyWie** [comment]
docker版本启动的时候指定端口就行了
