### ISSUE TITLE
edge接管下载bug

### ISSUE THREAD

**Issue by ismengx** [GopeedLab/browser-extension#35]
egde 125.0.2535.67
gopeed 1.5.7
extension 0.0.4
第一次在浏览器中下载使用的是edge自带下载器，gopeed未弹窗提示，第二次下载才会弹出gopeed下载框
出现概率不明
![image](https://github.com/GopeedLab/gopeed/assets/67355482/6ddd8ad4-5c9d-4be2-8fbe-70d0c4ecbdb2)

**Comment by monkeyWie** [comment]
是稳定复现吗？

**Comment by RoasDuck** [comment]
> 是稳定复现吗？

我这边试了几次，使用的是edge浏览器+扩展，任何情况下浏览器的首次下载都不接管，百分百出现第二次才接管的情况

**Comment by RoasDuck** [comment]
> 是稳定复现吗？
![2024-06-03_11-10-52](https://github.com/GopeedLab/browser-extension/assets/90942401/0ea3ed64-6a2f-4e13-9725-e074f5e7fb4c)

**Comment by ismengx** [comment]
> 是稳定复现吗？

是的，我这边和楼上的结果一样，在首次打开浏览器（没有任务栏后台）的情况下，第一次下载总是接管失败，第二次下载会接管成功
![image](https://github.com/GopeedLab/browser-extension/assets/67355482/89cffe89-ac51-4fe6-8a6f-6d2a45446364)
![image](https://github.com/GopeedLab/browser-extension/assets/67355482/8ff1992f-c69e-4cf4-90b8-58e7069bf650)

**Comment by monkeyWie** [comment]
我这里复现成功了一次之后就再也复现不了了，很怀疑是浏览器调度background.js的问题

**Comment by monkeyWie** [comment]
这个是浏览器机制的问题，目前没找到解决方案，先关闭咯
